package org.sk.sample.plugin.applauncher;

import org.apache.tools.ant.taskdefs.condition.Os;
import org.gradle.api.GradleException;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.logging.Logger;
import org.gradle.api.logging.Logging;
import org.gradle.api.provider.Property;
import org.gradle.api.services.BuildService;
import org.gradle.api.services.BuildServiceParameters;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;

public abstract class AppLauncher implements BuildService<AppLauncher.AppLauncherParams>, AutoCloseable {

    private static final Logger LOGGER = Logging.getLogger(AppLauncher.class);

    private Process process;


    interface AppLauncherParams extends BuildServiceParameters {
        Property<Integer> getPort();

        Property<String> getHost();

        DirectoryProperty getInstallationDirectory();

        DirectoryProperty getJavaHome();

        Property<String> getJavaOpts();
    }




    public void startApp() throws IOException {

        int port = getParameters().getPort().get();
        String host = getParameters().getHost().get();
        String installationDir = getParameters().getInstallationDirectory().get().getAsFile().getAbsolutePath();
        String javaHome = getParameters().getJavaHome().get().getAsFile().getAbsolutePath();
        String javaOpts = getParameters().getJavaOpts().get();

        LOGGER.info("in AppLauncher: installationDir: {}" , installationDir);
        LOGGER.info("in AppLauncher: javaHome: {}" , javaHome);
        LOGGER.info("in AppLauncher: javaOpts: {}" , javaOpts);
        LOGGER.info("in AppLauncher: port: {}" , port);
        LOGGER.info("in AppLauncher: host: {}" , host);

        LOGGER.info("starting app...");

        String scriptName = Os.isFamily(Os.FAMILY_WINDOWS) ? "application.bat" : "application";
        String startScript = getParameters().getInstallationDirectory().get().getAsFile().getAbsolutePath() + "/bin/" + scriptName;

        ProcessBuilder builder = new ProcessBuilder(startScript);
        builder.directory(getParameters().getInstallationDirectory().get().getAsFile());
        builder.environment().put("JAVA_HOME", javaHome);
        //send the host and port system properties to the application. the start script generated by
        //gradle Application plugin considers JAVA_OPTS.
        builder.environment().put("JAVA_OPTS", getParameters().getJavaOpts().get());
        File logsDir = new File(getParameters().getInstallationDirectory().get().getAsFile(), "logs");
        logsDir.mkdirs();
        File logFile = new File(logsDir, "app-launcher.log");
        builder.redirectOutput(logFile);
        builder.redirectError(logFile);
        builder.redirectErrorStream(true);

        this.process = builder.start();
        //wait a second to let the app start, 200 millis is probably enough too
        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
        }

        for (String line : Files.readAllLines(logFile.toPath())) {
            LOGGER.info(line);
            if (line.contains("Server started")) {
                LOGGER.info("Integration test app is ready!");
                break;
            }
        }

        if (!process.isAlive()) {
            throw new GradleException("Could not start the application for integration tests, " +
                    " server terminated abnormally. exit value: " + process.exitValue());
        }
    }


    @Override
    public void close() {
        if (process != null && process.isAlive()) {
            LOGGER.info("in close: stopping process...");
            process.destroy();
        }else{
            LOGGER.info("in close: process was already dead.");
        }
    }
}
